version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: skill-db
    environment:
      POSTGRES_DB: skill
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - skill_network

  skill-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skill-app
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://skill-db:5432/skill
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - skill_network

networks:
  skill_network:
