#actuator:
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9000
  servlet:
    context-path: /api/skill
spring:
  application:
    name: skill-service
  cloud:
    config:
      enabled: false
  #db
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/skill
    username: postgres
  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
#eurka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      registry-fetch-interval-seconds: 5
      instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true






