#actuator:
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9000
  servlet:
    context-path: /api
spring:
  application:
    name: skill-service
  cloud:
    config:
      enabled: false
  #db
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/skill
    username: postgres

  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
debug:
    enabled: true






