version: '3.9'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=skill
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data